// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aypzlxkbjifctbnypnup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5cHpseGtiamlmY3RibnlwbnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTk5MDAsImV4cCI6MjA2NDAzNTkwMH0.cORMwe5pmEnvbEPVOK9B9696_J7pbDpanzjC9XH6lmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);